# RedisBungee configuration file.
# you need Redis so get Redis from http://redis.io/ or install it from your package manager

# The Redis server you will use.
# these settings are ignored when cluster mode is enabled.
redis-server: 127.0.0.1
redis-port: 6379

# Cluster Mode
# enabling this option will enable cluster mode.
cluster-mode-enabled: false

# FORMAT:
# redis-cluster-servers:
# - host: 127.0.0.1
#   port: 2020
# - host: 127.0.0.1
#   port: 2021
# - host: 127.0.0.1
#   port: 2021

# you can set single server and Jedis will automatically discover cluster nodes,
# but might fail if this single redis node is down when Proxy startup, its recommended put the all the nodes
redis-cluster-servers:
  - host: 127.0.0.1
    port: 6379

# OPTIONAL: if your redis uses acl usernames set the username here. leave empty for no username.
redis-username: ""

# OPTIONAL but recommended: If your Redis server uses AUTH, set the required password.
redis-password: ""

# Maximum connections that will be maintained to the Redis server.
# The default is 10. This setting should be left as-is unless you have some wildly
# inefficient plugins or a lot of players.
max-redis-connections: 10

# since redis can support ssl by version 6 you can use SSL/TLS in redis bungee too!
# but there is more configuration needed to work see https://github.com/ProxioDev/RedisBungee/issues/18
# Keep note that SSL/TLS connections will decrease redis performance so use it when needed.
useSSL: false

# An identifier for this BungeeCord / Velocity instance. Will randomly generate if leaving it blank.
# Tip: you can set proxy id using Environment variable REDISBUNGEE_PROXY_ID which will override this config option
# before launch
proxy-id: "proxy-1"

# since RedisBungee Internally now uses JedisPooled instead of Jedis, JedisPool.
# which will break compatibility with old plugins that uses RedisBungee JedisPool
# so to mitigate this issue, RedisBungee will create an JedisPool for compatibility reasons.
# disabled by default
# ignored when cluster mode is enabled
enable-jedis-pool-compatibility: false

# max connections for the compatibility pool
compatibility-max-connections: 3

# restore old login behavior before 0.9.0 update
# enabled by default
# when true: when player login and there is old player with same uuid it will get disconnected as result and new player will log in
# when false: when a player login but login will fail because old player is still connected.
kick-when-online: true

# enabled by default
# this option tells RedisBungee handle motd and set online count, when motd is requested
# you can disable this when you want to handle motd yourself, use RedisBungee api to get total players when needed :)
handle-motd: true

# A list of IP addresses for which RedisBungee will not modify the response for, useful for automatic
# restart scripts.
# ignored if handle-motd is disabled.
exempt-ip-addresses: []

# disabled by default
# RedisBungee will attempt to connect player to last server that was stored.
reconnect-to-last-server: false

# Config version DO NOT CHANGE!!!!
config-version: 2
