# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: RedisBungee Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build with gradle
      run: ./gradlew shadowJar
    - name: Upload Bungee
      uses: actions/upload-artifact@v2.2.3
      with:
     # Artifact name
       name: RedisBungee-Bungee
     # Destination path
       path: RedisBungee-Bungee/build/libs/*
    - name: Upload Velocity
      uses: actions/upload-artifact@v2.2.3
      with:
        name: RedisBungee-Velocity
        path: RedisBungee-Velocity/build/libs/*
    - name: Upload API
      uses: actions/upload-artifact@v2.2.3
      with:
        name: RedisBungee-API
        path: RedisBungee-API/build/libs/*
